### ISSUE TITLE
Instantiating Clearwater-Riverine with a config file

### ISSUE THREAD

**Issue by sjordan29** [EcohydrologyTeam/ClearWater-riverine#48]
@aufdenkampe, @jrutyna, @xaviernogueira - as I'm thinking about #43, I was wondering if it might be useful to leverage a config file for Clearwater-Riverine. I feel like this approach could have a few advantages:

- Easy to set up for modelers who might not have as much Python experience
- Simple way to turn on / off modules (are they included in the config or not?)
- Easier to add flexibility in the number of general constituents to include
- More transparency on what information is needed for each of the modules from a user standpoint.

I'm envisioning clearwater looking for a `config.yml` file that looks something like this, which would be the only input for instantiating a Clearwater-Riverine model:

```yaml
- name: Sumwere Creek Plan 10
- description: Demo model
- path: ./sumwere_creek_p10.hdf
- diffusion_coefficient: 0.1
- modules:
  - gsm:
    - constituent-A:
      - initial_conditions: ./constituent_a_initial_conditions.csv
      - boundary_conditions: ./constituent_a_boundary_conditions.csv
      - order: 0
    - constituent-B:
      - initial_conditions: ./constituent_b_initial_conditions.csv
      - boundary_conditions: ./constituent_b_boundary_conditions.csv
      - order: 0
  - tsm:
    - initial_conditions: ./tsm_initial_conditions.csv
    - boundary_conditions: ./tsm_boundary_conditions.csv
    - meteo_parameters: ./tsm_meteo_parameters.csv
    - temp_parameters: ./tsm_temp_parameters.csv
```

To me, this feels like a more organized approach for setting up a Clearwater Riverine model than having a ton of optional inputs when instantiating the model, but I'm curious to hear what others thing from both a programming and modelling standpoint.

**Comment by jrutyna** [comment]
Yes, I am all for using a "config" file. Many of the other models I use have a similar method of model inputs. I can show you examples from other models if you are interested.

**Comment by aufdenkampe** [comment]
@sjordan29, I really, really like this idea. 
The General Lake Model (GLM) works like this
I also mentioned to @xaviernogueira that it might be the right approach for ClearWater-modules.

**Comment by sjordan29** [comment]
Great, I'll proceed with this. @jrutyna and @aufdenkampe it would be great if you could send me the config files for other models you've worked with like GLM that use this approach to help me figure out a good structure.

**Comment by xaviernogueira** [comment]
The config file can be a layer above the model. For Clearwater-modules it doesn't fit as well as inputs can be grids (I guess you could reference gridded files, but then I'd have to add a variety of `xarray` IO functions and have to be careful to make sure they are the same shapes).

That said, I am happy to build an IO "module" within Clearwater-modules to support whatever access patterns we want, whether it's a YAML, JSON, or just a Python TypedDict.

For running both models together it seems like a great choice! Maybe we should discuss, potentially after NSM gets farther, as the types of options available with that module are pretty diverse.

One note is that for YAML it is standard practice to not start unintended lines with a "-". I.e.,
```yaml
modules:
  - gsm:
    - constituent-A:
```
